# To check weather the number is postivie or negative or zero
'''A = int(input("Enter the number :"))
if A > 0:
    print("The number is postive ")
elif A < 0:
    print("The number is negative")
else:
    print("The number is Zero")

# even or odd 
B = int(input("Enter the number :"))
if B % 2 == 0:
    print("The number is Even")
else:
    print("The number is odd")
#5 answer is the output is A
# 6 answer is 1 , 2, 3, 4,5

while i >= 0:
    print(i)
    i -= 1
i = 2
while i <= 20:
    print(i)
    i += 2

i  = 1
while i <= 5:
    print(i)
    i += 1'''


i = 1
while i <= 10:
    print(5,"x",i , "=" , 5*i)
    i += 1


    